# Generated by Django 2.2.14 on 2022-08-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='age',
            field=models.CharField(choices=[('A', 'Adulto'), ('N', 'Niño'), ('BB', 'Bebe')], default='A', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Z', 'Zapatos'), ('B', 'Botas')], max_length=2),
        ),
    ]
