# Generated by Django 2.2.14 on 2022-08-11 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_respuestas'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestas',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Respuestas'),
        ),
    ]
